from dataclasses import dataclass
from typing import Optional, Dict, Any
from openai import OpenAI

from .metrics.faithfulness import FaithfulnessMetric
from .metrics.answer_relevancy import AnswerRelevancyMetric
from .metrics.context_relevancy import ContextRelevancyMetric

@dataclass
class RAGASResult:
    faithfulness: float
    answer_relevancy: float
    context_relevancy: float
    details: Dict[str, Any]

class RAGASEvaluator:
    """
    Automatic RAG evaluator using gapgpt API
    All metrics are computed without requiring reference data.
    """
    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.gapgpt.app/v1",
        llm_model: str = "gpt-4o",
        embedding_model: str = "text-embedding-3-small"
    ):
        self.client = OpenAI(api_key=api_key, base_url=base_url)
        self.llm_model = llm_model
        self.embedding_model = embedding_model

        # Create metric instances
        self.faithfulness = FaithfulnessMetric(self.client, llm_model)
        self.answer_relevancy = AnswerRelevancyMetric(self.client, llm_model, embedding_model)
        self.context_relevancy = ContextRelevancyMetric(self.client, llm_model)

    def evaluate(
        self,
        question: str,
        answer: str,
        context: Optional[str] = None,
        answer_relevancy_n: int = 3
    ) -> RAGASResult:
        """
        Compute all three metrics for a single RAG data sample

        Parameters:
            question: User question
            answer: Response generated by the RAG system
            context: Retrieved context (text)
            answer_relevancy_n: Number of questions for Answer Relevancy metric (default 3)
        """
        faith_score = self.faithfulness.compute(question, answer, context)
        ans_rel_score = self.answer_relevancy.compute(question, answer, answer_relevancy_n)
        ctx_rel_score = self.context_relevancy.compute(question, context)

        return RAGASResult(
            faithfulness=faith_score,
            answer_relevancy=ans_rel_score,
            context_relevancy=ctx_rel_score,
            details={
                "model": self.llm_model,
                "embedding_model": self.embedding_model,
                "answer_relevancy_n": answer_relevancy_n
            }
        )